// Code generated by MockGen. DO NOT EDIT.
// Source: internal/product/services/command/update_product.go

// Package command is a generated GoMock package.
package command

import (
	context "context"
	domain "r2-challenge/internal/product/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUpdateService is a mock of UpdateService interface.
type MockUpdateService struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceMockRecorder
}

// MockUpdateServiceMockRecorder is the mock recorder for MockUpdateService.
type MockUpdateServiceMockRecorder struct {
	mock *MockUpdateService
}

// NewMockUpdateService creates a new mock instance.
func NewMockUpdateService(ctrl *gomock.Controller) *MockUpdateService {
	mock := &MockUpdateService{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateService) EXPECT() *MockUpdateServiceMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockUpdateService) Update(ctx context.Context, product domain.Product) (domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, product)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUpdateServiceMockRecorder) Update(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateService)(nil).Update), ctx, product)
}
